cmd_drivers/gpu/arm/midgard/mali_kbase_strings.o := ./scripts/gcc-wrapper.py ./../prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androidkernel-gcc -Wp,-MD,drivers/gpu/arm/midgard/.mali_kbase_strings.o.d  -nostdinc -isystem /home/data/share/sdk-7.1/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Os --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r18p0-01rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/midgard/platform/"rk" -I./drivers/staging/android -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform_dummy -I -Idrivers/gpu/arm/midgard/../../../base -I./include/linux -Idrivers/gpu/arm/midgard/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_INSTRUMENTATION_LEVEL=0 -DMALI_RELEASE_NAME=\""r18p0-01rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_THIRDPARTY_PATH=../../drivers/gpu/arm/midgard/platform/"rk" -I./drivers/staging/android -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform_dummy -Idrivers/gpu/arm/midgard/../../../base -I./include/linux -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform/rk -Idrivers/gpu/arm/midgard/backend/gpu    -D"KBUILD_STR(s)=$(pound)s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_strings)"  -D"KBUILD_MODNAME=KBUILD_STR(midgard_kbase)" -c -o drivers/gpu/arm/midgard/.tmp_mali_kbase_strings.o drivers/gpu/arm/midgard/mali_kbase_strings.c

source_drivers/gpu/arm/midgard/mali_kbase_strings.o := drivers/gpu/arm/midgard/mali_kbase_strings.c

deps_drivers/gpu/arm/midgard/mali_kbase_strings.o := \
  drivers/gpu/arm/midgard/mali_kbase_strings.h \

drivers/gpu/arm/midgard/mali_kbase_strings.o: $(deps_drivers/gpu/arm/midgard/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/midgard/mali_kbase_strings.o):
